//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Documentation.
        /// </summary>
        public static string AddDocumentation {
            get {
                return ResourceManager.GetString("AddDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AskToDelete {
            get {
                return ResourceManager.GetString("AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Customer.
        /// </summary>
        public static string AssignCustomers {
            get {
                return ResourceManager.GetString("AssignCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Documentation.
        /// </summary>
        public static string AssignDocumentation {
            get {
                return ResourceManager.GetString("AssignDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Customers.
        /// </summary>
        public static string AssignedCustomers {
            get {
                return ResourceManager.GetString("AssignedCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string AssignedDocument {
            get {
                return ResourceManager.GetString("AssignedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Documentations.
        /// </summary>
        public static string AssignedDocuments {
            get {
                return ResourceManager.GetString("AssignedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Employees.
        /// </summary>
        public static string AssignedEmployees {
            get {
                return ResourceManager.GetString("AssignedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Vehicles.
        /// </summary>
        public static string AssignedVehicles {
            get {
                return ResourceManager.GetString("AssignedVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditors for Customer.
        /// </summary>
        public static string AuditorsForCustomer {
            get {
                return ResourceManager.GetString("AuditorsForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators Access.
        /// </summary>
        public static string BtnAccesoAdmin {
            get {
                return ResourceManager.GetString("BtnAccesoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditors Access.
        /// </summary>
        public static string BtnAccesoAuditores {
            get {
                return ResourceManager.GetString("BtnAccesoAuditores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Access.
        /// </summary>
        public static string BtnAccesoClientes {
            get {
                return ResourceManager.GetString("BtnAccesoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractors Access.
        /// </summary>
        public static string BtnAccesoContratistas {
            get {
                return ResourceManager.GetString("BtnAccesoContratistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Create.
        /// </summary>
        public static string BusinessTypesCreate {
            get {
                return ResourceManager.GetString("BusinessTypesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Delete.
        /// </summary>
        public static string BusinessTypesDelete {
            get {
                return ResourceManager.GetString("BusinessTypesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Details.
        /// </summary>
        public static string BusinessTypesDetail {
            get {
                return ResourceManager.GetString("BusinessTypesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Edit.
        /// </summary>
        public static string BusinessTypesEdit {
            get {
                return ResourceManager.GetString("BusinessTypesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template Create.
        /// </summary>
        public static string BusinessTypeTemplatesCreate {
            get {
                return ResourceManager.GetString("BusinessTypeTemplatesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template Delete.
        /// </summary>
        public static string BusinessTypeTemplatesDelete {
            get {
                return ResourceManager.GetString("BusinessTypeTemplatesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template Details.
        /// </summary>
        public static string BusinessTypeTemplatesDetail {
            get {
                return ResourceManager.GetString("BusinessTypeTemplatesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template Edit.
        /// </summary>
        public static string BusinessTypeTemplatesEdit {
            get {
                return ResourceManager.GetString("BusinessTypeTemplatesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters.
        /// </summary>
        public static string CodBusinessTypeLong {
            get {
                return ResourceManager.GetString("CodBusinessTypeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodBusinessTypeName {
            get {
                return ResourceManager.GetString("CodBusinessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CodBusinessTypeRequired {
            get {
                return ResourceManager.GetString("CodBusinessTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters.
        /// </summary>
        public static string CodDocumentationLong {
            get {
                return ResourceManager.GetString("CodDocumentationLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodDocumentationName {
            get {
                return ResourceManager.GetString("CodDocumentationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CodDocumentationRequired {
            get {
                return ResourceManager.GetString("CodDocumentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters.
        /// </summary>
        public static string CodDocumentationTemplateLong {
            get {
                return ResourceManager.GetString("CodDocumentationTemplateLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodDocumentationTemplateName {
            get {
                return ResourceManager.GetString("CodDocumentationTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CodDocumentationTemplateRequired {
            get {
                return ResourceManager.GetString("CodDocumentationTemplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 150 characters.
        /// </summary>
        public static string CompanyName_Long {
            get {
                return ResourceManager.GetString("CompanyName_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CompanyName_Name {
            get {
                return ResourceManager.GetString("CompanyName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string CompanyName_Required {
            get {
                return ResourceManager.GetString("CompanyName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordNoMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Code.
        /// </summary>
        public static string ContractCode {
            get {
                return ResourceManager.GetString("ContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Create.
        /// </summary>
        public static string ContractCreate {
            get {
                return ResourceManager.GetString("ContractCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Delete.
        /// </summary>
        public static string ContractDelete {
            get {
                return ResourceManager.GetString("ContractDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ContractDescription {
            get {
                return ResourceManager.GetString("ContractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 250 characters.
        /// </summary>
        public static string ContractDescription_Long {
            get {
                return ResourceManager.GetString("ContractDescription_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Description is required.
        /// </summary>
        public static string ContractDescription_Required {
            get {
                return ResourceManager.GetString("ContractDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Edit.
        /// </summary>
        public static string ContractEdit {
            get {
                return ResourceManager.GetString("ContractEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Create.
        /// </summary>
        public static string ContractorsCreate {
            get {
                return ResourceManager.GetString("ContractorsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Delete.
        /// </summary>
        public static string ContractorsDelete {
            get {
                return ResourceManager.GetString("ContractorsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Details.
        /// </summary>
        public static string ContractorsDetail {
            get {
                return ResourceManager.GetString("ContractorsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Edit.
        /// </summary>
        public static string ContractorsEdit {
            get {
                return ResourceManager.GetString("ContractorsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts for Contractor.
        /// </summary>
        public static string ContractsForContractor {
            get {
                return ResourceManager.GetString("ContractsForContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ContractStartDate {
            get {
                return ResourceManager.GetString("ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2016 All Rights Reserved. Sicco!. Privacy and Terms.
        /// </summary>
        public static string CopyRightFooter {
            get {
                return ResourceManager.GetString("CopyRightFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Create.
        /// </summary>
        public static string CustomerCreate {
            get {
                return ResourceManager.GetString("CustomerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Delete.
        /// </summary>
        public static string CustomerDelete {
            get {
                return ResourceManager.GetString("CustomerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string CustomerDetail {
            get {
                return ResourceManager.GetString("CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Edit.
        /// </summary>
        public static string CustomerEdit {
            get {
                return ResourceManager.GetString("CustomerEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 150 characters.
        /// </summary>
        public static string DescBusinessTypeLong {
            get {
                return ResourceManager.GetString("DescBusinessTypeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescBusinessTypeName {
            get {
                return ResourceManager.GetString("DescBusinessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescBusinessTypeRequired {
            get {
                return ResourceManager.GetString("DescBusinessTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 150 characters.
        /// </summary>
        public static string DescDocumentationLong {
            get {
                return ResourceManager.GetString("DescDocumentationLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DescDocumentationName {
            get {
                return ResourceManager.GetString("DescDocumentationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescDocumentationName1 {
            get {
                return ResourceManager.GetString("DescDocumentationName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescDocumentationRequired {
            get {
                return ResourceManager.GetString("DescDocumentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 150 characters.
        /// </summary>
        public static string DescDocumentationTemplateLong {
            get {
                return ResourceManager.GetString("DescDocumentationTemplateLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescDocumentationTemplateName {
            get {
                return ResourceManager.GetString("DescDocumentationTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string DescDocumentationTemplateRequired {
            get {
                return ResourceManager.GetString("DescDocumentationTemplateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string DocEntityType {
            get {
                return ResourceManager.GetString("DocEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must attach a Document.
        /// </summary>
        public static string DocumentAttach_Required {
            get {
                return ResourceManager.GetString("DocumentAttach_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string DocumentFiles {
            get {
                return ResourceManager.GetString("DocumentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Create.
        /// </summary>
        public static string DocumentsCreate {
            get {
                return ResourceManager.GetString("DocumentsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Delete.
        /// </summary>
        public static string DocumentsDelete {
            get {
                return ResourceManager.GetString("DocumentsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Details.
        /// </summary>
        public static string DocumentsDetail {
            get {
                return ResourceManager.GetString("DocumentsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Edit.
        /// </summary>
        public static string DocumentsEdit {
            get {
                return ResourceManager.GetString("DocumentsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template Create.
        /// </summary>
        public static string DocumentsTemplateCreate {
            get {
                return ResourceManager.GetString("DocumentsTemplateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template Delete.
        /// </summary>
        public static string DocumentsTemplateDelete {
            get {
                return ResourceManager.GetString("DocumentsTemplateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template Details.
        /// </summary>
        public static string DocumentsTemplateDetail {
            get {
                return ResourceManager.GetString("DocumentsTemplateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template Edit.
        /// </summary>
        public static string DocumentsTemplateEdit {
            get {
                return ResourceManager.GetString("DocumentsTemplateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Document.
        /// </summary>
        public static string DownloadDocument {
            get {
                return ResourceManager.GetString("DownloadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerg. Phone Number.
        /// </summary>
        public static string EmergPhoneNumber_Name {
            get {
                return ResourceManager.GetString("EmergPhoneNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee Contract.
        /// </summary>
        public static string EmployeeContractDelete {
            get {
                return ResourceManager.GetString("EmployeeContractDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Create.
        /// </summary>
        public static string EmployeeCreate {
            get {
                return ResourceManager.GetString("EmployeeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Delete.
        /// </summary>
        public static string EmployeeDelete {
            get {
                return ResourceManager.GetString("EmployeeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Edit.
        /// </summary>
        public static string EmployeeEdit {
            get {
                return ResourceManager.GetString("EmployeeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentification Number is Required.
        /// </summary>
        public static string EmployeeIdentNumber_Required {
            get {
                return ResourceManager.GetString("EmployeeIdentNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type.
        /// </summary>
        public static string EmployeeRelationshipType {
            get {
                return ResourceManager.GetString("EmployeeRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Type is EmployeeRelationshipType_Required.
        /// </summary>
        public static string EmployeeRelationshipType_Required {
            get {
                return ResourceManager.GetString("EmployeeRelationshipType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees for Contractor.
        /// </summary>
        public static string EmployeesForContractor {
            get {
                return ResourceManager.GetString("EmployeesForContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditors.
        /// </summary>
        public static string EtyAuditors {
            get {
                return ResourceManager.GetString("EtyAuditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        public static string EtyBusinessType {
            get {
                return ResourceManager.GetString("EtyBusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        public static string EtyBusinessTypes {
            get {
                return ResourceManager.GetString("EtyBusinessTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type List.
        /// </summary>
        public static string EtyBusinessTypesTitle {
            get {
                return ResourceManager.GetString("EtyBusinessTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template.
        /// </summary>
        public static string EtyBusinessTypeTemplate {
            get {
                return ResourceManager.GetString("EtyBusinessTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Template.
        /// </summary>
        public static string EtyBusinessTypeTemplates {
            get {
                return ResourceManager.GetString("EtyBusinessTypeTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Templates List.
        /// </summary>
        public static string EtyBusinessTypeTemplatesTitle {
            get {
                return ResourceManager.GetString("EtyBusinessTypeTemplatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string EtyContract {
            get {
                return ResourceManager.GetString("EtyContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string EtyContractor {
            get {
                return ResourceManager.GetString("EtyContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string EtyContractors {
            get {
                return ResourceManager.GetString("EtyContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor List.
        /// </summary>
        public static string EtyContractorsTitle {
            get {
                return ResourceManager.GetString("EtyContractorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string EtyContracts {
            get {
                return ResourceManager.GetString("EtyContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string EtyCustomer {
            get {
                return ResourceManager.GetString("EtyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string EtyCustomers {
            get {
                return ResourceManager.GetString("EtyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string EtyCustomerTitle {
            get {
                return ResourceManager.GetString("EtyCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string EtyDocumentation {
            get {
                return ResourceManager.GetString("EtyDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string EtyDocumentations {
            get {
                return ResourceManager.GetString("EtyDocumentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template.
        /// </summary>
        public static string EtyDocumentationsTemplate {
            get {
                return ResourceManager.GetString("EtyDocumentationsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template.
        /// </summary>
        public static string EtyDocumentationTemplate {
            get {
                return ResourceManager.GetString("EtyDocumentationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation Template List.
        /// </summary>
        public static string EtyDocumentationTemplateTitle {
            get {
                return ResourceManager.GetString("EtyDocumentationTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation List.
        /// </summary>
        public static string EtyDocumentationTitle {
            get {
                return ResourceManager.GetString("EtyDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EtyEmployee {
            get {
                return ResourceManager.GetString("EtyEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Contract.
        /// </summary>
        public static string EtyEmployeeContract {
            get {
                return ResourceManager.GetString("EtyEmployeeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EtyEmployees {
            get {
                return ResourceManager.GetString("EtyEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string EtyPresentation {
            get {
                return ResourceManager.GetString("EtyPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string EtyPresentations {
            get {
                return ResourceManager.GetString("EtyPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string EtyUser {
            get {
                return ResourceManager.GetString("EtyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string EtyVehicle {
            get {
                return ResourceManager.GetString("EtyVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Contract.
        /// </summary>
        public static string EtyVehicleContract {
            get {
                return ResourceManager.GetString("EtyVehicleContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string EtyVehicles {
            get {
                return ResourceManager.GetString("EtyVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string FirstName_Long {
            get {
                return ResourceManager.GetString("FirstName_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string FirstName_Required {
            get {
                return ResourceManager.GetString("FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Form.
        /// </summary>
        public static string FormLogin {
            get {
                return ResourceManager.GetString("FormLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value must be between 1 and 10.
        /// </summary>
        public static string Importance_Range {
            get {
                return ResourceManager.GetString("Importance_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance is required.
        /// </summary>
        public static string Importance_Required {
            get {
                return ResourceManager.GetString("Importance_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to confirm the email to be able to enter the Application..
        /// </summary>
        public static string IsNotEmailConfirmed {
            get {
                return ResourceManager.GetString("IsNotEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string LastName_Long {
            get {
                return ResourceManager.GetString("LastName_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string LastName_Required {
            get {
                return ResourceManager.GetString("LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Administrators.
        /// </summary>
        public static string LoginAdminTitle {
            get {
                return ResourceManager.GetString("LoginAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Contractors.
        /// </summary>
        public static string LoginContractorsTitle {
            get {
                return ResourceManager.GetString("LoginContractorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Customers.
        /// </summary>
        public static string LoginCustomersTitle {
            get {
                return ResourceManager.GetString("LoginCustomersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLogin {
            get {
                return ResourceManager.GetString("PasswordLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicity.
        /// </summary>
        public static string Periodicity {
            get {
                return ResourceManager.GetString("Periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string PeriodID {
            get {
                return ResourceManager.GetString("PeriodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters.
        /// </summary>
        public static string PhoneNumber_Long {
            get {
                return ResourceManager.GetString("PhoneNumber_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber_Name {
            get {
                return ResourceManager.GetString("PhoneNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string PresentationCount {
            get {
                return ResourceManager.GetString("PresentationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Date.
        /// </summary>
        public static string PresentationDate {
            get {
                return ResourceManager.GetString("PresentationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Delete.
        /// </summary>
        public static string PresentationDelete {
            get {
                return ResourceManager.GetString("PresentationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string PresentationState {
            get {
                return ResourceManager.GetString("PresentationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen. Matrix.
        /// </summary>
        public static string RegenerateMatrix {
            get {
                return ResourceManager.GetString("RegenerateMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Date.
        /// </summary>
        public static string RejectedDate {
            get {
                return ResourceManager.GetString("RejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Contractors.
        /// </summary>
        public static string ReportsFromContractors {
            get {
                return ResourceManager.GetString("ReportsFromContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Employees.
        /// </summary>
        public static string ReportsFromEmployees {
            get {
                return ResourceManager.GetString("ReportsFromEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Vehicles.
        /// </summary>
        public static string ReportsFromVehicles {
            get {
                return ResourceManager.GetString("ReportsFromVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequirementStatus {
            get {
                return ResourceManager.GetString("RequirementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string ResourceIdentification {
            get {
                return ResourceManager.GetString("ResourceIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        public static string ResourceType {
            get {
                return ResourceManager.GetString("ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict Access.
        /// </summary>
        public static string RestrictAccess {
            get {
                return ResourceManager.GetString("RestrictAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicco -  Sistema Administracion de Contratistas.
        /// </summary>
        public static string SiccoMainPageTitle {
            get {
                return ResourceManager.GetString("SiccoMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        public static string SocialSecurityNumber {
            get {
                return ResourceManager.GetString("SocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist documentation.
        /// </summary>
        public static string SP_MSG_EXIST_DOCUMENTATION {
            get {
                return ResourceManager.GetString("SP_MSG_EXIST_DOCUMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist requirements for Customer on Period.
        /// </summary>
        public static string SP_MSG_EXIST_REQUIREMENT {
            get {
                return ResourceManager.GetString("SP_MSG_EXIST_REQUIREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        public static string Take {
            get {
                return ResourceManager.GetString("Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Date.
        /// </summary>
        public static string TakenDate {
            get {
                return ResourceManager.GetString("TakenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken For.
        /// </summary>
        public static string TakenFor {
            get {
                return ResourceManager.GetString("TakenFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters.
        /// </summary>
        public static string TaxIdNumber_Long {
            get {
                return ResourceManager.GetString("TaxIdNumber_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        public static string TaxIdNumber_Name {
            get {
                return ResourceManager.GetString("TaxIdNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id is required.
        /// </summary>
        public static string TaxIdNumber_Required {
            get {
                return ResourceManager.GetString("TaxIdNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Assign Documentation.
        /// </summary>
        public static string ToAssignDocumentation {
            get {
                return ResourceManager.GetString("ToAssignDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Assign Employee.
        /// </summary>
        public static string ToAssignEmployee {
            get {
                return ResourceManager.GetString("ToAssignEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Assign Vehicle.
        /// </summary>
        public static string ToAssignVehicle {
            get {
                return ResourceManager.GetString("ToAssignVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sicco.
        /// </summary>
        public static string TtlBienvenida {
            get {
                return ResourceManager.GetString("TtlBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLogin {
            get {
                return ResourceManager.GetString("UsernameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Create.
        /// </summary>
        public static string UsersCreate {
            get {
                return ResourceManager.GetString("UsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Delete.
        /// </summary>
        public static string UsersDelete {
            get {
                return ResourceManager.GetString("UsersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UsersDetail {
            get {
                return ResourceManager.GetString("UsersDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Edit.
        /// </summary>
        public static string UsersEdit {
            get {
                return ResourceManager.GetString("UsersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users for Contractor.
        /// </summary>
        public static string UsersForContractor {
            get {
                return ResourceManager.GetString("UsersForContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vehicle Contract.
        /// </summary>
        public static string VehicleContractDelete {
            get {
                return ResourceManager.GetString("VehicleContractDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Create.
        /// </summary>
        public static string VehicleCreate {
            get {
                return ResourceManager.GetString("VehicleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Delete.
        /// </summary>
        public static string VehicleDelete {
            get {
                return ResourceManager.GetString("VehicleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string VehicleDescription {
            get {
                return ResourceManager.GetString("VehicleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 250 characters.
        /// </summary>
        public static string VehicleDescription_Long {
            get {
                return ResourceManager.GetString("VehicleDescription_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Description is required.
        /// </summary>
        public static string VehicleDescription_Required {
            get {
                return ResourceManager.GetString("VehicleDescription_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Edit.
        /// </summary>
        public static string VehicleEdit {
            get {
                return ResourceManager.GetString("VehicleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification.
        /// </summary>
        public static string VehicleIdentificationNumber {
            get {
                return ResourceManager.GetString("VehicleIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 50 characters.
        /// </summary>
        public static string VehicleIdentificationNumber_Long {
            get {
                return ResourceManager.GetString("VehicleIdentificationNumber_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification is required.
        /// </summary>
        public static string VehicleIdentificationNumber_Required {
            get {
                return ResourceManager.GetString("VehicleIdentificationNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles for Contractor.
        /// </summary>
        public static string VehiclesForContractor {
            get {
                return ResourceManager.GetString("VehiclesForContractor", resourceCulture);
            }
        }
    }
}
