CREATE FUNCTION [dbo].[fxGetPeriodo] (@Fecha AS DATETIME)  
RETURNS INT
AS  
BEGIN 

	DECLARE @RET INT

	SET @RET = (CONVERT(INT, DATEPART(YEAR, @Fecha))*100) + CONVERT(INT, DATEPART(MONTH, @Fecha))

	RETURN @RET
END