// <auto-generated />
namespace SiccoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201605151501445_migration_security_002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201605151501445_migration_security_002));
        
        string IMigrationMetadata.Id
        {
            get { return "201605181232441_201605151501445_migration_security_002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
